=== teja2490/Web-API-Code-Challenge/SPXFlowWebApiTest/XMLData/ProductsSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://spxflow.com/products/XMLSchema"
    elementFormDefault="qualified"
    xmlns="http://spxflow.com/products/XMLSchema"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="id" type="xs:long"/>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="shortDescription" type="xs:string"/>
  <xs:element name="brand" type="brandName"/>
  <xs:element name="user" type="xs:string"/>
  
  <xs:attribute name="datePublished" type="xs:dateTime" />

  <xs:element name="rating">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="1"/>
        <xs:maxInclusive value="5"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>  
  
  <xs:simpleType name="brandName">
      <xs:restriction base="xs:string">
        <xs:enumeration value="APV"/>
        <xs:enumeration value="Airpel"/>
        <xs:enumeration value="PowerTeam"/>
      </xs:restriction>    
  </xs:simpleType>

  <xs:element name="comment">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:maxLength value="256"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name ="review">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="rating"></xs:element>
        <xs:element ref="comment"></xs:element>
        <xs:element ref="user"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:element name ="reviews">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="review" maxOccurs="unbounded"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name ="product">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="title"/>
        <xs:element ref="shortDescription"/>
        <xs:element ref="brand"/>
        <xs:element ref="reviews"/>
      </xs:sequence>
      <xs:attribute ref="datePublished"/>
    </xs:complexType>
  </xs:element>

  <xs:element name ="products">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="product" maxOccurs="unbounded"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== teja2490/Web-API-Code-Challenge/SPXFlowWebApiTest/App_Data/productsData.xml
<?xml version="1.0" encoding="utf-8"?>
<products xmlns="http://spxflow.com/products/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://spxflow.com/products/XMLSchema ProductsSchema.xsd">
  <product>
    <id>1</id>
    <title>APV Gaulin Mono-Block</title>
    <shortDescription>An integrated design of cylinders (3 or 5), pump valves, plunger lubrication and inlet/outlet in one block.</shortDescription>
    <brand>APV</brand>
    <reviews>
      <review>
        <rating>5</rating>
        <comment>This is a great product.</comment>
        <user>John D.</user>
      </review>
      <review>
        <rating>1</rating>
        <comment>Had some issues with this product</comment>
        <user>Anonymous</user>
      </review>
    </reviews>
  </product>
  <product>
    <id>2</id>
    <title>Gasketed Plate Heat Exchanger - Industrial</title>
    <shortDescription>Gasketed Plate Heat Exchanger for Industrial Applications.</shortDescription>
    <brand>APV</brand>
    <reviews>
      <review>
        <rating>3</rating>
        <comment>This product review can't exceed 256 characters. If I put more than that, my review will be truncated!</comment>
        <user>John D.</user>
      </review>
    </reviews>
  </product>
</products>
